### PR TITLE
Prepare dependencies for 0.21.0

### PR DESCRIPTION
**Pull request by rhuss**
/hole until source-pkg 0.6.3 is released and this PR update with the vendor files

### CODE REVIEW

**Comment by dsimansk** [comment]
@hurss FYI you should also bump test setup dependencies. 
https://github.com/knative-sandbox/kn-plugin-source-kafka/blob/master/test/e2e-tests.sh#L26-L27
https://github.com/knative-sandbox/kn-plugin-source-kafka/blob/master/test/e2e-tests.sh#L45

**Comment by rhuss** [comment]
/unhold

@maximilien @dsimansk @navidshaikh I think we are good to merge this one, I then can cut the the 0.21 release

**Comment by rhuss** [comment]
@dsimansk thanks, but I would need an `/approve`, too

**Pull request merged**
