### PR TITLE
Update Knative dependency for release-0.23

### PR DESCRIPTION
**Pull request by chizhg**

### CODE REVIEW

**Comment by dprotaso** [comment]
hmm..  I feel like it should be approved given I'm a release lead for 0.24

**Comment by rhuss** [comment]
> hmm.. I feel like it should be approved given I'm a release lead for 0.24

OWNERS setup looks good, no idea why this didn't work. Maybe because it is assigned to me ?

nevermind, 
/lgtm
/approve

**Comment by dprotaso** [comment]
It’s using the owners file from the release branch

**Pull request merged**
