### PR TITLE
Update README to adopt repo change

### PR DESCRIPTION
**Pull request by daisy-ycguo**
## Description

Update document to adopt repo change

## Changes

* Update README to adopt repo change

### CODE REVIEW

**Review by navidshaikh — COMMENTED** [review]
@daisy-ycguo : looks like the go-coverage CI job is still picked up from old config, I had to open a fresh PR to pick the latest config for CI tests PR.

**Comment by daisy-ycguo** [comment]
> @daisy-ycguo : looks like the go-coverage CI job is still picked up from old config, I had to open a fresh PR to pick the latest config for CI tests PR.

Thank you. I think CI works good now.

**Review by maximilien — APPROVED** [review]
/lgtm

**Pull request merged**
